[template]
# 排除不需要包含在模板产物中的目录和文件
exclude = [
    "target",
    "web/*",
    "bin",
    "*.pid",
    "*.out",
    "*.err",
    ".history",
    ".DS_Store"
]


[placeholders]
project_name = { prompt = "Enter project name", default = "rsweb", type = "string" }
