name: Release

on:
  push:
    tags:
      - "v*"



jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: ${{env.PROJECT_NAME}}-linux
            binary: rsweb
          - os: windows-latest
            artifact: rsweb-windows
            binary: rsweb.exe
          - os: macos-latest
            artifact: rsweb-macos
            binary: rsweb

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build Web
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd web
          npm i
          npm run build

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: target/release/${{ matrix.binary }}
